version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
      #- NODE_ENV=development
    depends_on:
      - backend

volumes:
  mongo-data:
  # backend-node-modules:
  # frontend-node-modules:
